// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izsrfqewjpdnpxciozfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6c3JmcWV3anBkbnB4Y2lvemZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTE1OTksImV4cCI6MjA2MjA2NzU5OX0.x5To4d9Lw0cJVBTyfbC4B93To-thGA74QuI_CJeczrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);